Single requests session
osisoft/sample-ocs-sample_libraries-python pull request #31
Opened 2021-11-05 18:58 UTC by cbardini

2021-11-05 19:01 UTC, derekendres approved these changes

2021-11-05 19:02 UTC, derekendres requested changes

2021-11-05 19:02 UTC, derekendres commented on ocs_sample_library_preview/BaseClient.py
> +        self.__session = requests.Session()
does this say this is deprecated? https://2.python-requests.org/projects/3/_modules/requests/sessions/ (very bottom)

2021-11-05 19:05 UTC, derekendres commented on ocs_sample_library_preview/BaseClient.py
> +        self.__session = requests.Session()
wait thats a different thing, all good

2021-11-05 19:05 UTC, derekendres approved these changes

2021-11-09 10:34 UTC, anton-dahlin approved these changes

2021-11-09 17:21 UTC, merged